security.jwt.token.secret-key: my-secret-key
server:
  port: 1243

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bank_db
    username: user_db
    password: pass_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect